language: python
sudo: false
matrix:
  include:
    - arch: arm64
      TOXENV: py27
    - arch: amd64
      TOXENV: py27
install:
 - travis_retry pip install tox
 # virtualenv 14 installs pip8 under tox which breaks py32
 - |
    if [ "$TOXENV" = "py32" ]; then
        pip install 'virtualenv<14'
    fi
script: tox
